#! /bin/sh

sxhkd &
xrandr --output DP-1 --mode 1920x1080 --pos 1000x0 --rotate normal --output DVI-D-1 --primary --mode 1920x1080 --pos 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 0x1080 --rotate normal &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		0
bspc config window gap			20
bspc config focus_follows_pointer	true
#bspc config top_padding		24

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config single_monocle	true
bspc config gapless_monocle	true

bspc config active_border_color "#990000"
bspc config normal_border_color "#222222"

# rules
bspc rule -a Pavucontrol state=floating

# load software on boot (desktop background, compositor, monitor rotation)
feh --bg-center ~/.Background.jpeg
compton -f
