#! /bin/sh

sxhkd &
feh --bg-scale ~/Pictures/Backgrounds/132gsgbthds.jpeg &
polybar top &

# monitor display settings
bspc monitor -d				One Two Three Four Five

# aesthetic changes
bspc config top_padding -m DVI-D-1	20
bspc config border_width        	1
bspc config window_gap         	 	10
bspc config active_border_color		"#5bb9e9"
bspc config normal_border_color		"#5bb9e9"
bspc config focused_border_color	"#ba66ba"

# functional changes
bspc config focus_follows_pointer	true
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle		true

# rules for windows to follow
bspc rule -a Pavucontrol state=floating
bspc rule -a Shutter state=floating
bspc rule -a Qalculate-gtk state=floating

# applications to launch at boot
compton -f
